show databases;
create database Address_Book_Service_DB;
use Address_Book_Service_DB;
select database();
drop database Address_Book_Service_DB;
show databases;
create table Address_Book(fName varchar(20) primary key, lName varchar(20), address varchar(20), city varchar (20), state varchar (20), zip varchar (10), phoneNumber varchar(15),email varchar(25));
drop table Address_Book;
insert into Address_Book(fName,lName,address,city,state,zip,phoneNumber,email) values('Neeta','Mourya','Dayalband','Bsp','CG',495001,9875235232,'neeta@gmail.com');
insert into Address_Book(fName,lName,address,city,state,zip,phoneNumber,email) values('Prakash','kashyap','Dayalband','Bsp','CG',495001,9875235232,'prakash@gmail.com');
select * from Address_Book;
UPDATE Address_Book SET fName = 'Neetu', City= 'BSP' WHERE fName = 'Neeta';
DELETE FROM Address_Book WHERE fName='Prakash';
select fName from Address_Book where state='CG' and city='BSP';
